// <auto-generated/>
#pragma warning disable CS0618
using KiotaPosts.RestfulBookerClient.Auth;
using KiotaPosts.RestfulBookerClient.Booking;
using KiotaPosts.RestfulBookerClient.Ping;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.RestfulBookerClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RestfulBookerClient : BaseRequestBuilder
    {
        /// <summary>The auth property</summary>
        public global::KiotaPosts.RestfulBookerClient.Auth.AuthRequestBuilder Auth
        {
            get => new global::KiotaPosts.RestfulBookerClient.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The booking property</summary>
        public global::KiotaPosts.RestfulBookerClient.Booking.BookingRequestBuilder Booking
        {
            get => new global::KiotaPosts.RestfulBookerClient.Booking.BookingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ping property</summary>
        public global::KiotaPosts.RestfulBookerClient.Ping.PingRequestBuilder Ping
        {
            get => new global::KiotaPosts.RestfulBookerClient.Ping.PingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.RestfulBookerClient.RestfulBookerClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RestfulBookerClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "https://restful-booker.herokuapp.com";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
