// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaPosts.RestfulBookerClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum BadAuthResponse_reason
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "bad credentials")]
        #pragma warning disable CS1591
        BadCredentials,
        #pragma warning restore CS1591
    }
}
