// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace KiotaPosts.RestfulBookerClient.Models
{
    /// <summary>
    /// Represents a hotel booking in the system.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Booking : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Any other needs the guest has</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Additionalneeds { get; set; }
#nullable restore
#else
        public string Additionalneeds { get; set; }
#endif
        /// <summary>The bookingdates property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KiotaPosts.RestfulBookerClient.Models.Booking_bookingdates? Bookingdates { get; set; }
#nullable restore
#else
        public global::KiotaPosts.RestfulBookerClient.Models.Booking_bookingdates Bookingdates { get; set; }
#endif
        /// <summary>Whether the deposit has been paid or not</summary>
        public bool? Depositpaid { get; set; }
        /// <summary>First name of the guest who made the booking</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Firstname { get; set; }
#nullable restore
#else
        public string Firstname { get; set; }
#endif
        /// <summary>Last name for the guest who made the booking</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Lastname { get; set; }
#nullable restore
#else
        public string Lastname { get; set; }
#endif
        /// <summary>The total price for the booking</summary>
        public int? Totalprice { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.RestfulBookerClient.Models.Booking"/> and sets the default values.
        /// </summary>
        public Booking()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::KiotaPosts.RestfulBookerClient.Models.Booking"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::KiotaPosts.RestfulBookerClient.Models.Booking CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::KiotaPosts.RestfulBookerClient.Models.Booking();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "additionalneeds", n => { Additionalneeds = n.GetStringValue(); } },
                { "bookingdates", n => { Bookingdates = n.GetObjectValue<global::KiotaPosts.RestfulBookerClient.Models.Booking_bookingdates>(global::KiotaPosts.RestfulBookerClient.Models.Booking_bookingdates.CreateFromDiscriminatorValue); } },
                { "depositpaid", n => { Depositpaid = n.GetBoolValue(); } },
                { "firstname", n => { Firstname = n.GetStringValue(); } },
                { "lastname", n => { Lastname = n.GetStringValue(); } },
                { "totalprice", n => { Totalprice = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("additionalneeds", Additionalneeds);
            writer.WriteObjectValue<global::KiotaPosts.RestfulBookerClient.Models.Booking_bookingdates>("bookingdates", Bookingdates);
            writer.WriteBoolValue("depositpaid", Depositpaid);
            writer.WriteStringValue("firstname", Firstname);
            writer.WriteStringValue("lastname", Lastname);
            writer.WriteIntValue("totalprice", Totalprice);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
